---
version: "3"

services:
  apigw:
    container_name: "vc_apigw"
    image: "${DOCKERHUB_FQDN}/dc4eu/apigw:${TAG}"
    
    restart: always
    volumes:
      - ${PWD}/config.yaml:/config.yaml:ro
      - ${PWD}/log:/var/log/sunet
    expose:
      - 8080
    ports:
      - "${APIGW_HOST_PORT:-8080}:8080"
    depends_on:
      - redis
      - mongo
    environment:
      - "VC_CONFIG_YAML=config.yaml"

  verifier:
    container_name: "vc_verifier"
    image: "${DOCKERHUB_FQDN}/dc4eu/verifier:${TAG}"
    restart: always
    volumes:
      - ${PWD}/config.yaml:/config.yaml:ro
    depends_on:
      - redis
      - mongo
    environment:
      - "VC_CONFIG_YAML=config.yaml"

  registry:
    container_name: "vc_registry"
    image: "${DOCKERHUB_FQDN}/dc4eu/registry:${TAG}"
    restart: always
    volumes:
      - ${PWD}/config.yaml:/config.yaml:ro
    depends_on:
      - redis
      - mongo
    environment:
      - "VC_CONFIG_YAML=config.yaml"

  persistent:
    container_name: "vc_persistent"
    image: "${DOCKERHUB_FQDN}/dc4eu/persistent:${TAG}"
    restart: always
    volumes:
      - ${PWD}/config.yaml:/config.yaml:ro
    depends_on:
      - redis
      - mongo
    environment:
      - "VC_CONFIG_YAML=config.yaml"

  redis:
    image: redis:alpine
    container_name: "vc_redis"
    restart: always
    expose:
      - 6373
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mongo:
    image: mongo:4.0.10
    container_name: "vc_mongo"
    restart: always
    expose:
      - 27017
    volumes:
      - mongo_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: vc_jaeger
    restart: always
    expose:
      - 16686
      - 4317
      - 4318
    ports:
      - "${JAEGER_HOST_PORT:-16686}:16686"
    environment:
      - "COLLECTOR_OTLP_ENABLED=true"

volumes:
  redis_data:
  mongo_data:
